### ISSUE TITLE
Website in README

### ISSUE THREAD

**Issue by raffaem** [zeileis/ivreg#16]
I think we should put the website in the README

https://zeileis.github.io/ivreg/

**Comment by zeileis** [comment]
Hmm, the usefulness of such a link depends on how you view it. There are three main ways to view the README file, I think:

* <https://zeileis.github.io/ivreg/>: The README is turned into the landing page of the pkgdown site. A "self reference" is probably not needed there.
* <https://github.com/zeileis/ivreg/>: The README is shown on the GitHub project page but this already links to the GitHub pages as well. So another link within the README is not essential, I think.
* <https://CRAN.R-project.org/web/packages/ivreg/readme/README.html>: The README is also shown as a standalone page on CRAN. Here, a link to the GitHub page would be useful. But then again, this is shown on the CRAN package page itself.

So overall I'm not sure what would be a useful way to integrate such a link in the README...

**Comment by raffaem** [comment]
Maybe I missed the link in the About section.

Thanks!

**Comment by zeileis** [comment]
It wasn't as prominent. After answering your question I saw that there is a checkbox that let's me display the GitHub pages URL explicitly (rather than only through the corresponding button).

Thanks for the suggestion!
