### ISSUE TITLE
Bibliographic references

### ISSUE THREAD

**Issue by raffaem** [zeileis/ivreg#18]
The [vignette](https://zeileis.github.io/ivreg/articles/Diagnostics-for-2SLS-Regression.html) briefly describe the 3 tests provided by the summary.

Can we put bibliographic references for such tests? Where they are explained in more mathematical details? Or where have you taken the implementation from?

**Comment by zeileis** [comment]
Thanks for the pointer. The tests are described in many standard econometrics textbooks covering instrumental variables and 2SLS. If I recall correctly, I used the Greene (2003) textbook back when I implemented them. I have used this now both in the vignette and on the `ivreg` manual page.
