### ISSUE TITLE
Confidence interval and prediction intervals

### ISSUE THREAD

**Issue by ghost** [zeileis/ivreg#19]
Doesn't `ivreg` implement confidence and prediction intervals?

The following called on an ivreg object return just the prediction, not the interval around it:

````
predict(mod2, newdata=newdf, interval="confidence", level=0.99)
predict(mod2, newdata=newdf, interval="prediction", level=0.99)
````

**Comment by zeileis** [comment]
Yes, that is correct, at the moment these arguments are not supported by `predict.ivreg` and just vanish in the `...` arguments.

One way to obtain standard errors for predictions from `ivreg` is via [marginaleffects](https://vincentarelbundock.github.io/marginaleffects/), e.g.

```
predictions(mod2, newdata = newdf)
```

**Comment by john-d-fox** [comment]
We added an augmented version of `predict.ivreg()` that has `se.fit`, `interval`, `level`, and `weights` arguments. The implementation is preliminary.

If you have the **remotes** package installed, you can try it by installing the development version of **ivreg** via `remotes::install_github("zeileis/ivreg")`.

**Comment by zeileis** [comment]
Finally, this updated version is also available on CRAN now.
