### ISSUE TITLE
bug in hatvalues(model, type="maximum")

### ISSUE THREAD

**Issue by vsyrgkanis** [zeileis/ivreg#21]
It seems to me that this line:
https://github.com/zeileis/ivreg/blob/234b00e60c2531c9cf713043e8a10b7a965204ce/R/ivregDiagnostics.R#L291

should actually be:
```R
hats[, "stage_1"] / mean1
```

Currently because this is not divided, the stage 2 hatvalues is always the maximum and `hatvalues(model, type="maximum")` essentially always returns the stage 2 hatvalues.

**Comment by john-d-fox** [comment]
I'll take a closer look tomorrow, but, yes, it looks like it should be 
hats[, "stage_1"]/mean1, and from the commented-out code, it also looks 
like the computation was previously done correctly.

John

**Comment by vsyrgkanis** [comment]
Thank you John!

**Comment by zeileis** [comment]
Version 0.6-4 of `ivreg` is now also released on CRAN. Thanks for reporting the bug, @vsyrgkanis! Thanks for fixing/updating the code, @john-d-fox!
