### ISSUE TITLE
pkgdown github action produces error messages

### ISSUE THREAD

**Issue by john-d-fox** [zeileis/ivreg#4]
I added a pkgdown github action and it produces a couple of error messages -- see the Actions tab

**Comment by john-d-fox** [comment]
I tried the version of the pkgdown github action suggested by Daniel and it appears to work. I don't like simply parroting code without fully understanding it, so at some point one of us should look at this more closely. I'm leaving this issue open for the time-being.

**Comment by strengejacke** [comment]
My impression is that there are temporary issues every now and then, which appear and disappear with no clear reason. It's hard to find out if errors can be resolved by fixing the yaml-action file itself, or if it's a temporary thing. That's indeed a downside of this automatic action, compared to manually building the pkgdown website.

**Comment by zeileis** [comment]
Switching to the current pkgdown GHA from r-lib fixed the problems, see: https://github.com/zeileis/ivreg/commit/a9f98645c56673afa95faeac714ac447c3ac8cf7
